<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>QuizPractice.Web</AssemblyName>
    <RootNamespace>QuizPractice.Web</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuizPractice.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\appsettings.json" Link="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\questions.json" Link="questions.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
